name: Build and Deploy to Network Share
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Copy build to network share
      shell: powershell
      run: |
        $repoPath = "${{ github.workspace }}\dist"
        
        # Ścieżki plików źródłowych
        $fileJs = Join-Path $repoPath "DuniRequestRegistry.js"
        $fileCss = Join-Path $repoPath "DuniRequestRegistry.css"
        
        # Destinations
        $destinationJs = "\\pozmda02\w$\Test_arkurb\wwwroot\js\app"
        $destinationCss = "\\pozmda02\w$\Test_arkurb\wwwroot\css\app\DuniRequestRegistry"
        
        # Copy files
        Copy-Item -Path $fileJs -Destination $destinationJs -Force
        Copy-Item -Path $fileCss -Destination $destinationCss -Force
